---
title: "NDT"
subtitle: "CVRL"
author: |
  Yuchan KIM
  
date: 2026.04.01

output:
  xaringan::moon_reader:
    lib_dir: libs
    css: 
      - "default"
      - "default-fonts"
      - "../Xaringan_Example/swan/swan.css"
      - "../Xaringan_Example/swan/swan-fonts.css"
      - "../Xaringan_Example/swan/swan-all-fonts.css"
      - "../Xaringan_Example/swan/tachyons_ext.css"
    nature:
      ratio: "16:9"
      highlightStyle: "github"
      highlightLines: true
      countIncrementalSlides: false
      beforeInit: ["../Xaringan_Example/swan/macros.js"] 
      scale: true


---
## How to get mean and covariance?
.nt-02.f-90[
  - covariance_estimation.cpp]

```cpp
Vector4d sum_points = Vector4d::Zero();
Matrix4d sum_covs   = Matrix4d::Zero();

for (int j = 0; j < num_found; j++) 
{
  const auto& pt = points[k_indices[j]];
  sum_points += pt;
  sum_covs += pt * pt.transpose();
}

Eigen::Vector4d mean = sum_points / num_found;
Eigen::Matrix4d cov = (sum_covs - mean * sum_points.transpose()) / num_found;
```
.f-90[  
  - `sum_points` : $S_{\mu} = \sum_{j=1}^{k} p_j$, &ensp; `sum_covs` : $S_{\Sigma} = \sum_{j=1}^{k} p_j p_j^T$
- mean: $\mu_i = \frac{S_{\mu}}{k}$, $p_i$ 주변 이웃점들의 local mean을 의미
- 공분산 : $\Sigma_i = \frac{S_{\Sigma}}{k} - \mu_i \mu_i^T = \frac{S_{\Sigma} - \mu_i \cdot S_{\mu}^T}{k}$, 기준점 $p_i$ 주변 k개 이웃점들의 local covariance 의미
]
---
## How to get mean and covariance?
.nt-02.f-90[
  - covariance_estimation.cpp]

```cpp
case CovarianceEstimationParams::EIG: {
  Eigen::SelfAdjointEigenSolver<Eigen::Matrix3d> eig;
  eig.computeDirect(cov.block<3, 3>(0, 0));

  covs[i].setZero();
  covs[i].block<3, 3>(0, 0) = eig.eigenvectors()
      * params.eigen_values.asDiagonal()
      * eig.eigenvectors().inverse();
}
```

.f-90[
- `params.eigen_values`의 기본값은 `(1e-3, 1.0, 1.0)`
$$
\Sigma_i^{\text{EIG}} = V \, \mathrm{diag}(10^{-3},\; 1.0,\; 1.0) \, V^{-1}
$$
- **법선방향**은 $10^{-3}$로 작음, 나머지 두축은 분산이 1.0으로 평범
- 각 포인트만의 $\Sigma_i$이 존재
]
---
## How to get mean and covariance?
.nt-02.f-90[
  - gaussian_voxelmap_cpu.cpp]
  
```cpp
void GaussianVoxel::add(const Setting& setting, const PointCloud& points, size_t i) {
  if (finalized) {
    this->finalized  = false;
    this->mean      *= num_points;   // 합산값으로 복원
    this->cov       *= num_points;   // 합산값으로 복원
  }
  num_points++;
  this->mean += points.points[i];   // 위치 누적
  this->cov  += points.covs[i];     // 포인트별 공분산 누적
}
```
.f-90[
  - mean은 finalize전 좌표들의 합으로, $\mu_{sum} = \sum_{i=1}^{N} p_i,$ 
- cov은 finalize전이면 point들의 공분산들의 합, $\Sigma_{sum} = \sum_{i=1}^{N} \Sigma_i$
- finalize가 true 경우, **mean과 cov는 이미 N으로 나눠진 평균값이므로 다시 합산값**으로 복원
  - $\bar\mu = \frac{1}{N} \cdot \sum_{i=1}^{N} p_i$, &ensp; $\bar\Sigma = \frac{1}{N} \cdot \sum_{i=1}^{N} \Sigma_i$

]
---
## How to get mean and covariance?
.nt-02.f-90[
  - gaussian_voxelmap_cpu.cpp]
  
```cpp
void GaussianVoxel::finalize() {
  if (finalized) return;
  mean /= num_points;   // 가평균
  cov  /= num_points;   // 가분산
  finalized = true;
}
```

.f-90[
  - finalize() 호출 시, 합산된 mean과 cov를 N으로 나눠서 평균값으로 변환
-  $\bar\mu = \frac{1}{N} \cdot \sum_{i=1}^{N} p_i$ , **가평균**
-  $\bar\Sigma = \frac{1}{N} \cdot \sum_{i=1}^{N} \Sigma_i$, **가분산**
-  여기서의 cov는 $\frac{1}{N}\Sigma(p_i-\bar\mu)(p_i-\bar\mu)^T$가 아닌, voxel안의 점들의 분산의 평균을 의미하므로 가분산이라함.
]

---
## How to get mean and covariance?
.nt-02.f-90[
  - covariance_estimation.cpp : 각 점 $p_i$에 대한 $\Sigma_i$ 계산
- gaussian_voxelmap_cpu.cpp : $\Sigma_i$들을 voxel안에서 평균을 통해 $\bar{\Sigma}_i$ 계산
  - voxel내 포인트들의 **공간적 분포**가 아닌 포인트들의 **이웃 공분산의 평균**을 사용 그래서 **가분산**
- 가평균 : voxel안의 들어온 점들의 평균
$$\bar\mu = \frac{1}{N} \cdot \sum_{i=1}^{N} p_i$$
- 가분산 : voxel안의 들어온 점들의 공분산의 평균
$$\bar\Sigma = \frac{1}{N} \cdot \sum_{i=1}^{N} \Sigma_i$$
]
  
